### ISSUE TITLE
Sketch uses 31028 bytes (101%) of program storage space. Maximum is 30720 bytes.

### ISSUE THREAD

**Issue by gigajuad** [ArcaEge/grbl-28byj-48-pen-plotter-servo#1]
Im trying to upload this to a nano (i know this version is intended for uno but every grbl version so far has worked with nano)

is there any way to reduce the size just slightly so that it can fit into nano's program storage?

**Comment by ArcaEge** [comment]
Try uploading normal GRBL to the nano. Do you get the same error? If so, close the issue and post it to the GRBL repo.

**Comment by gigajuad** [comment]
Hi, thnx for the comment
this repo's config has corexy enabled, resulting in a larger size, disabling it made it small enough to upload to the nano.

**Comment by ArcaEge** [comment]
Sorry, forgot to uncomment that line. Still, it seems strange that it compiles fine on an uno, but not on a nano. They both have the ATmega328P with 32kb flash and a nano is functionally same as an uno, so maybe it might also be a bug with the Arduino IDE???

**Comment by gigajuad** [comment]
probably cuz of the compiler version, idk which one im using, but glad it worked
